name: philosophylab
favicon: null
layout_spectrum: 0.26043
typography_spectrum: 0.81738
title: "don't try this at home"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050005'
    - '#cda080'
    - '#fffed9'
    - '#81545e'
    - '#301822'
  brandStrength: 0.75
  lightness: 0.8248388341162354
  saturation: 0.535251465626061
  rhythmicContrast: 0.034260790795087814
purpose: []
